### ISSUE TITLE
Build fails with @cosmjs/tendermint-rpc@0.37.0 due to missing package.json fields

### ISSUE THREAD

**Issue by Miguiz** [cosmos/cosmjs#1917]
Hi

I'm experiencing a build issue after upgrading to `@cosmjs/tendermint-rpc@0.37.0` and later. The build fails because TypeScript cannot resolve the module.

## The Problem:

Starting from version 0.37.0, the `package.json` no longer includes the `main` and `types` fields. This breaks compatibility with TypeScript projects using `moduleResolution: "node"` (the legacy/classic resolution).

## Error:

Cannot find module '@cosmjs/tendermint-rpc' or its corresponding type declarations.
There are types at '.../node_modules/@cosmjs/tendermint-rpc/build/index.d.ts',
but this result could not be resolved under your current 'moduleResolution' setting.

## What changed:

- Version 0.36.0: Has `"main": "build/index.js"` and `"types": "build/index.d.ts"` → Works
- Version 0.37.0: Only has `exports` field → Breaks with legacy module resolution

## Impact:

Projects using `moduleResolution: "node"` cannot build with version 0.37.0+ without changing their TypeScript configuration.

## Possible solutions:

1. Add back the `main` and `types` fields for backward compatibility (recommended), as otherwise updates will not be possible
2. Or document this breaking change in the changelog/README

Thanks for your help

**Comment by webmaster128** [comment]
In #1940 and #1942 I bring back main/types in order to restore bundlephobia support. They will be included in 0.37.1 and 0.38.1 (and probably main as well). So you can start trying those versions.

Mid term I think the solution explained above is the right (tm) way I guess.
